import Foundation
import XCTest
@testable import SolvioApprovalsKit

final class TaskActionTests: XCTestCase {
    func testAccountDisplayLabelDoesNotChangeBoundIdentityOrRequest() throws {
        let first = ActionServiceAccount(service: "gmail", account: "configured_mail", resource: "me", label: "Privat")
        let renamed = ActionServiceAccount(service: "gmail", account: "configured_mail", resource: "me", label: "Mein Konto")
        var form = TaskActionForm(); form.kind = .gmail; form.mailMode = .exact
        form.recipient = "recipient@example.invalid"; form.subject = "Betreff"; form.body = "Text"
        form.reconcileAccounts([first])
        let before = try form.request(accounts: [first])
        XCTAssertEqual(first, renamed)
        XCTAssertEqual(try form.request(accounts: [renamed]), before)
        XCTAssertEqual(try form.account(accounts: [renamed]).displayLabel, "Mein Konto")
    }
    private let accounts = [ActionServiceAccount(service: "calendar", account: "configured_account", resource: "primary"),
                            ActionServiceAccount(service: "gmail", account: "configured_mail", resource: "me")]
    private func action() throws -> AppTaskAction {
        try AppTaskAction(actionID: "calendar1", service: "calendar", operation: "create", account: "configured_account",
            target: ["calendar_id": "primary"], payload: ["summary": .string("Fahrrad \"München\" 🚲"),
                "start": .string("2026-09-15T09:00:00+02:00"), "end": .string("2026-09-15T10:00:00+02:00"),
                "all_day": .bool(false), "description": .string("Zeile 1\nZeile 2"), "location": .string("Werkstatt")])
    }
    private func request() throws -> AppTaskActionRequest { try AppTaskActionRequest(actions: [action()]) }
    private func body(_ request: AppTaskActionRequest? = nil) throws -> AppTaskBody {
        try AppTaskBody(scope: "action", objective: "Lege den Fahrradtermin für München an.", targetRepo: "",
                        requestID: "request-action-001", actionRequest: request ?? self.request())
    }

    func testNestedCanonicalHashMatchesRealPythonCoreIncludingUnicodeAndBoolean() throws {
        let body = try body()
        // Generated by real Core canonical_task_body + protocol.canonical_bytes.
        XCTAssertEqual(body.requestDigest, "88df710e55304f971f4ed118c2809a48c46364bf65a9afc41a550ba2fbd50c19")
        let encoded = try JSONEncoder().encode(body)
        XCTAssertEqual(try JSONDecoder().decode(AppTaskBody.self, from: encoded), body)
        let decoded = try XCTUnwrap(JSONSerialization.jsonObject(with: encoded) as? [String: Any])
        XCTAssertNotNil(decoded["action_request"])
        XCTAssertTrue(String(decoding: body.canonicalBytes(), as: UTF8.self).contains("\"all_day\":false"))
    }

    func testOldResearchAndBuildBodiesHaveNoActionKeyAndKeepCanonicalBytes() throws {
        for scope in ["research", "build"] {
            let body = try AppTaskBody(scope: scope, objective: "Prüfe diesen bisherigen Auftrag.", targetRepo: "", requestID: "request-old-001")
            let expected = ApprovalProtocol.canonicalBytes(["scope": .string(scope), "objective": .string(body.objective),
                "target_repo": .string(""), "client_request_id": .string(body.client_request_id)])
            XCTAssertEqual(body.canonicalBytes(), expected)
            XCTAssertFalse(String(decoding: try JSONEncoder().encode(body), as: UTF8.self).contains("action_request"))
            XCTAssertThrowsError(try AppTaskBody(scope: scope, objective: body.objective, targetRepo: "", requestID: body.client_request_id,
                                                actionRequest: request()))
        }
        XCTAssertThrowsError(try AppTaskBody(scope: "action", objective: "Erledige diesen gebundenen Auftrag.", targetRepo: "", requestID: "request-empty-001"))
    }

    func testRetryMetadataBindsEveryActionByteAndRestoresOnlyExactAction() throws {
        var draft = TaskStartDraft()
        let request = try request()
        let first = try draft.prepare(scope: "action", objective: "Erledige den gebundenen Termin.", targetRepo: "", actionRequest: request)
        let retry = TaskStartRetryBinding(body: first, coreID: "core", deviceID: "phone")
        var restarted = TaskStartDraft()
        XCTAssertEqual(try restarted.prepare(scope: first.scope, objective: first.objective, targetRepo: "", retry: retry,
            coreID: "core", deviceID: "phone", actionRequest: request), first)
        let original = try action()
        for mutation in ["account", "target", "summary", "start", "description", "location"] {
            var payload = original.payload
            if mutation == "summary" { payload[mutation] = .string("Anderer Termin") }
            if mutation == "start" { payload[mutation] = .string("2026-09-15T09:30:00+02:00") }
            if mutation == "description" || mutation == "location" { payload[mutation] = .string("Geändert") }
            let changed = try AppTaskAction(actionID: original.action_id, service: original.service, operation: original.operation,
                account: mutation == "account" ? "another_account" : original.account,
                target: mutation == "target" ? ["calendar_id": "other"] : original.target, payload: payload)
            let newRequest = try AppTaskActionRequest(actions: [changed])
            XCTAssertNil(retry.restore(scope: first.scope, objective: first.objective, targetRepo: "", coreID: "core", deviceID: "phone", actionRequest: newRequest))
            let prepared = try draft.prepare(scope: first.scope, objective: first.objective, targetRepo: "", actionRequest: newRequest)
            XCTAssertNotEqual(prepared.client_request_id, first.client_request_id)
            XCTAssertNotEqual(prepared.requestDigest, first.requestDigest)
        }
        let metadata = String(decoding: try JSONEncoder().encode(retry), as: UTF8.self)
        XCTAssertFalse(metadata.contains("Werkstatt")); XCTAssertFalse(metadata.contains("configured_account"))
    }

    func testAccountSelectionRequiresExactlyOneMeasuredServiceIdentity() throws {
        XCTAssertEqual(try ActionServiceAccount.unique(accounts, service: "calendar"), accounts[0])
        XCTAssertThrowsError(try ActionServiceAccount.unique([], service: "calendar"))
        XCTAssertThrowsError(try ActionServiceAccount.unique([accounts[0], accounts[0]], service: "calendar"))
        XCTAssertThrowsError(try ActionServiceAccount.unique([ActionServiceAccount(service: "calendar", account: "https://other.example", resource: "primary")], service: "calendar"))
        XCTAssertThrowsError(try ActionServiceAccount.unique([ActionServiceAccount(service: "gmail", account: "configured_mail", resource: "other")], service: "gmail"))
    }

    func testMultipleAccountsRequireAnOfferedExplicitChoiceAndBindItIntoRetry() throws {
        let second = ActionServiceAccount(service: "calendar", account: "work_account", resource: "work_calendar")
        let offered = accounts + [second]
        var form = TaskActionForm(); form.title = "Fahrradtermin"; form.reconcileAccounts(offered)
        XCTAssertNil(form.selectedAccount)
        XCTAssertThrowsError(try form.request(accounts: offered))
        try form.selectAccount(second, accounts: offered)
        let request = try form.request(accounts: offered)
        XCTAssertEqual(request.actions[0].account, second.account)
        XCTAssertEqual(request.actions[0].target, ["calendar_id": second.resource])
        let first = try AppTaskBody(scope: "action", objective: form.objective, targetRepo: "", requestID: "chosen-account-001", actionRequest: request)
        let retry = TaskStartRetryBinding(body: first, coreID: "core", deviceID: "phone")
        try form.selectAccount(accounts[0], accounts: offered)
        XCTAssertNil(retry.restore(scope: "action", objective: form.objective, targetRepo: "", coreID: "core", deviceID: "phone",
                                   actionRequest: try form.request(accounts: offered)))
        try form.selectAccount(second, accounts: offered)
        XCTAssertEqual(retry.restore(scope: "action", objective: form.objective, targetRepo: "", coreID: "core", deviceID: "phone",
                                     actionRequest: try form.request(accounts: offered)), first)
        let forged = ActionServiceAccount(service: "calendar", account: second.account, resource: "unoffered_calendar")
        XCTAssertThrowsError(try form.selectAccount(forged, accounts: offered))
        XCTAssertThrowsError(try form.selectAccount(accounts[1], accounts: offered))
        XCTAssertEqual(form.selectedAccount, second)
    }

    func testDisappearedSingletonKeepsItsBindingUntilExplicitReplacement() throws {
        var form = TaskActionForm(); form.title = "Fahrradtermin"; form.reconcileAccounts(accounts)
        let original = try form.request(accounts: accounts)
        let replacement = ActionServiceAccount(service: "calendar", account: accounts[0].account, resource: "changed_calendar")
        for offered in [[], [replacement], [replacement, accounts[1]]] {
            form.reconcileAccounts(offered)
            XCTAssertEqual(form.selectedAccount, accounts[0])
            XCTAssertThrowsError(try form.request(accounts: offered)) { error in
                XCTAssertEqual(error as? TaskActionError, .selectedAccountUnavailable)
            }
        }
        form.reconcileAccounts(accounts)
        XCTAssertEqual(try form.request(accounts: accounts), original)
        form.reconcileAccounts([replacement])
        try form.selectAccount(replacement, accounts: [replacement])
        XCTAssertEqual(try form.request(accounts: [replacement]).actions[0].target, ["calendar_id": "changed_calendar"])
        XCTAssertNotEqual(try form.request(accounts: [replacement]), original)
    }

    func testServiceSwitchKeepsSeparateChoicesAndCannotReuseForeignResource() throws {
        let extraMail = ActionServiceAccount(service: "gmail", account: "work_mail", resource: "me")
        let offered = accounts + [extraMail]
        var form = TaskActionForm(); form.title = "Termin"; form.reconcileAccounts(offered)
        XCTAssertEqual(form.selectedAccount, accounts[0])
        form.kind = .gmail
        XCTAssertNil(form.selectedAccount)
        XCTAssertThrowsError(try form.account(accounts: offered))
        try form.selectAccount(extraMail, accounts: offered)
        form.kind = .calendar
        XCTAssertEqual(form.selectedAccount, accounts[0])
        form.kind = .gmail
        XCTAssertEqual(form.selectedAccount, extraMail)
        XCTAssertThrowsError(try form.account(accounts: accounts))
    }

    func testCalendarFormBindsVisibleMinutesAndFrozenTimezoneAcrossDST() throws {
        let parser = ISO8601DateFormatter()
        var form = TaskActionForm(now: Date(timeIntervalSince1970: 1_000), timeZone: try XCTUnwrap(TimeZone(identifier: "Europe/Berlin")))
        form.reconcileAccounts(accounts)
        form.title = "Zeitumstellung"
        form.start = try XCTUnwrap(parser.date(from: "2026-10-25T02:30:42+02:00"))
        form.end = try XCTUnwrap(parser.date(from: "2026-10-25T02:45:25+01:00"))
        let action = try form.request(accounts: accounts).actions[0]
        XCTAssertEqual(action.payload["start"], .string("2026-10-25T02:30:00+02:00"))
        XCTAssertEqual(action.payload["end"], .string("2026-10-25T02:45:00+01:00"))
        XCTAssertEqual(form.timeZoneIdentifier, "Europe/Berlin")
        let originalDefault = NSTimeZone.default
        defer { NSTimeZone.default = originalDefault }
        NSTimeZone.default = try XCTUnwrap(TimeZone(identifier: "America/New_York"))
        XCTAssertEqual(try form.request(accounts: accounts).actions[0], action)
        form.end = form.start
        XCTAssertThrowsError(try form.request(accounts: accounts))
    }

    func testMailFormCreatesOnlyExactDraftAndBindsRecipientSubjectAndBody() throws {
        var form = TaskActionForm(); form.kind = .gmail; form.mailMode = .exact; form.reconcileAccounts(accounts)
        form.recipient = "friend@example.invalid"; form.subject = "Fahrrad"; form.body = "Zeile 1\nZeile 2"
        let first = try form.request(accounts: accounts), action = first.actions[0]
        XCTAssertEqual(action.service, "gmail"); XCTAssertEqual(action.operation, "create_draft")
        XCTAssertEqual(action.target, ["mailbox": "me", "to": "friend@example.invalid", "reply_to_message": ""])
        XCTAssertEqual(action.payload["body"], .string(form.body))
        for key in ["recipient", "subject", "body"] {
            var changed = form
            if key == "recipient" { changed.recipient = "other@example.invalid" }
            if key == "subject" { changed.subject += "!" }
            if key == "body" { changed.body += "!" }
            XCTAssertNotEqual(try changed.request(accounts: accounts), first)
        }
        form.recipient += "\nBcc:other@example.invalid"
        XCTAssertThrowsError(try form.request(accounts: accounts))
    }

    func testMailCompositionDefaultsToBoundInstructionAndRecipientWithExactRetry() throws {
        var form = TaskActionForm(); form.kind = .gmail; form.reconcileAccounts(accounts)
        form.recipient = "friend@example.invalid"
        form.instruction = "Bitte freundlich nach dem Termin fragen.\nKeine Zusage erfinden. 😀"
        form.subject = "Unsichtbarer alter Betreff"; form.body = "Unsichtbarer alter Text"
        XCTAssertEqual(form.mailMode, .compose)
        let request = try form.request(accounts: accounts), action = request.actions[0]
        XCTAssertEqual(action.operation, "compose_draft")
        XCTAssertEqual(action.target, ["mailbox": "me", "to": form.recipient])
        XCTAssertEqual(action.payload, ["instruction": .string(form.instruction)])
        let body = try AppTaskBody(scope: "action", objective: form.objective, targetRepo: "",
                                   requestID: "compose-request-001", actionRequest: request)
        // Real Core request_digest with this Unicode instruction and fixed recipient.
        XCTAssertEqual(body.requestDigest, "250e44c11a6c977d3e6f12dbe12036f300a9a1089ba89e114cfca44a620deb11")
        let retry = TaskStartRetryBinding(body: body, coreID: "core", deviceID: "phone")
        XCTAssertEqual(retry.restore(scope: body.scope, objective: body.objective, targetRepo: "", coreID: "core", deviceID: "phone", actionRequest: request), body)
        for mutation in ["instruction", "recipient", "mode"] {
            var changed = form
            if mutation == "instruction" { changed.instruction += "!" }
            if mutation == "recipient" { changed.recipient = "another@example.invalid" }
            if mutation == "mode" { changed.mailMode = .exact }
            XCTAssertNil(retry.restore(scope: body.scope, objective: body.objective, targetRepo: "", coreID: "core", deviceID: "phone",
                actionRequest: try changed.request(accounts: accounts)))
        }
        XCTAssertEqual(try JSONDecoder().decode(AppTaskBody.self, from: JSONEncoder().encode(body)), body)
    }

    func testComposedMailRejectsMissingOversizedInstructionsRecipientsAndExtraFields() throws {
        var form = TaskActionForm(); form.kind = .gmail; form.reconcileAccounts(accounts)
        form.recipient = "friend@example.invalid"
        for value in ["", " \n", String(repeating: "x", count: 4001), "\u{0}"] {
            form.instruction = value; XCTAssertThrowsError(try form.request(accounts: accounts))
        }
        form.instruction = String(repeating: "x", count: 4000)
        let action = try form.request(accounts: accounts).actions[0]
        for recipient in ["", "a@example.invalid,b@example.invalid", "a@example.invalid\nBcc:b@example.invalid"] {
            form.recipient = recipient; XCTAssertThrowsError(try form.request(accounts: accounts))
        }
        XCTAssertThrowsError(try AppTaskAction(actionID: action.action_id, service: action.service, operation: action.operation,
            account: action.account, target: action.target.merging(["cc": "other@example.invalid"]) { a, _ in a }, payload: action.payload))
        XCTAssertThrowsError(try AppTaskAction(actionID: action.action_id, service: action.service, operation: action.operation,
            account: action.account, target: action.target, payload: action.payload.merging(["body": .string("Unbound text")]) { a, _ in a }))
    }

    func testDecodingRejectsExtraFieldsUnknownOperationsAndNaiveTimes() throws {
        let raw = try XCTUnwrap(JSONSerialization.jsonObject(with: JSONEncoder().encode(body())) as? [String: Any])
        for mutation in ["top", "action", "payload", "operation", "time"] {
            var changed = raw
            if mutation == "top" { changed["authority"] = true }
            else {
                var envelope = try XCTUnwrap(changed["action_request"] as? [String: Any])
                var actions = try XCTUnwrap(envelope["actions"] as? [[String: Any]])
                if mutation == "action" { actions[0]["capability"] = "unbound" }
                if mutation == "operation" { actions[0]["operation"] = "send_draft" }
                if mutation == "payload" || mutation == "time" {
                    var payload = try XCTUnwrap(actions[0]["payload"] as? [String: Any])
                    payload[mutation == "time" ? "start" : "url"] = mutation == "time" ? "2026-09-15T09:00:00" : "https://other.example"
                    actions[0]["payload"] = payload
                }
                envelope["actions"] = actions; changed["action_request"] = envelope
            }
            XCTAssertThrowsError(try JSONDecoder().decode(AppTaskBody.self, from: JSONSerialization.data(withJSONObject: changed)))
        }
    }

    @MainActor
    func testLostActionResponseRetriesExactBodyWithFreshAttestationAndRejectsChangedAction() async throws {
        let body = try body(), key = Data(repeating: 1, count: 32).base64EncodedString()
        func challenge(_ body: AppTaskBody, nonce: String) throws -> AppTaskChallenge {
            let binding: [String: Any] = ["protocol_version": 1, "type": "app_task_start_binding",
                "core_instance_id": "core-test", "principal_id": "owner-test", "device_id": "phone-test",
                "nonce": nonce, "request_digest": body.requestDigest, "enrollment_id": "enrollment-test",
                "app_attest_key_id": key, "approval_key_sha256": String(repeating: "a", count: 64)]
            let raw = try JSONSerialization.data(withJSONObject: binding, options: [.sortedKeys, .withoutEscapingSlashes])
            return AppTaskChallenge(nonce: nonce, requestDigest: body.requestDigest, expiresAt: 2_000_000_000,
                                    bindingB64: raw.base64EncodedString())
        }
        let old = try challenge(body, nonce: String(repeating: "aa", count: 32))
        let original = try action()
        let changed = try AppTaskAction(actionID: original.action_id, service: original.service,
            operation: original.operation, account: "different_account", target: original.target, payload: original.payload)
        let different = try self.body(AppTaskActionRequest(actions: [changed]))
        XCTAssertThrowsError(try old.clientDataHash(body: different, coreID: "core-test", deviceID: "phone-test",
            appAttestKeyID: key, now: 1_999_999_990))
        let attempt = TaskStartAttempt()
        var sent = [AppTaskBody](), signatures = [Data]()
        for index in 0...1 {
            do {
                _ = try await attempt.send(body: body, coreID: "core-test", deviceID: "phone-test", appAttestKeyID: key,
                    challenge: { try challenge($0, nonce: String(repeating: index == 0 ? "aa" : "bb", count: 32)) },
                    sign: { signatures.append($0); return Data([1]) },
                    submit: { task, _ in
                        sent.append(task)
                        if index == 0 { throw URLError(.networkConnectionLost) }
                        return AppTaskAccepted(taskID: "at-test", runID: "ar-test", state: "CREATED")
                    }, now: { 1_999_999_990 })
                XCTAssertEqual(index, 1)
            } catch { XCTAssertEqual(index, 0) }
        }
        XCTAssertEqual(sent, [body, body]); XCTAssertEqual(signatures.count, 2)
        XCTAssertNotEqual(signatures[0], signatures[1])
    }
}
