#!/usr/bin/env python3
"""Golden vectors for the C3 conversation-message contract (N8_C3_API.md §2.3/§2.4).

Deterministic and dependency-free: the canonical form is exactly what the Core's
``P.canonical_bytes`` does (``json.dumps(sort_keys=True, separators=(",", ":"),
ensure_ascii=False)``), the digest is sha256 over those bytes, and the
clientDataHash is ``sha256(DOMAIN + b"\\0" + binding_bytes)``. The Core test for
``conversation/message_proof.py`` must reproduce every hex value in the emitted
JSON; the Swift Kit test reads the same file. Synthetic identifiers only.

Usage:  python3 Tests/conversation_message_vector.py > Tests/SolvioApprovalsKitTests/Vectors/app_conversation_message_v1.json
"""
from __future__ import annotations

import base64
import hashlib
import json

DOMAIN = b"SOLVIO_APP_CONVERSATION_MESSAGE_V1"
BINDING_TYPE = "app_conversation_message_binding"
VOICE_DOMAIN = b"SOLVIO_VOICE_SESSION_V1"
TASK_DOMAIN = b"SOLVIO_APP_TASK_START_V1"


def canonical_bytes(payload: dict) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def digest(payload: dict) -> str:
    return hashlib.sha256(canonical_bytes(payload)).hexdigest()


def domain_hash(domain: bytes, raw: bytes) -> str:
    return hashlib.sha256(domain + b"\0" + raw).hexdigest()


CONVERSATION = "c-0123456789abcdef"
CLIENT_MESSAGE = "msg-20260918-0001"

plain = {
    "conversation_id": CONVERSATION,
    "client_message_id": CLIENT_MESSAGE,
    "text": "Danke — prüf bitte das Café-Layout 👩🏽‍💻 und sag mir,\nwas fehlt.",
}
targeted = dict(plain, client_message_id="msg-20260918-0002",
                text="Ergänze im selben Auftrag den März.",
                target={"task_id": "at-0123456789abcdef", "run_id": "ar-0123456789abcdef", "revision": 2})
document = dict(plain, client_message_id="msg-20260918-0003",
                text="Fasse dieses Dokument zusammen.",
                attachments={"operation": "extract_text", "format": "txt",
                             "content_b64": base64.b64encode("Hallo Welt\n".encode()).decode("ascii")})
files = dict(plain, client_message_id="msg-20260918-0004",
             text="Werte diese Tabelle aus.",
             attachments={"operation": "process_files", "files": [
                 {"name": "umsatz.csv", "content_b64": base64.b64encode(b"monat,betrag\n2026-03,12.50\n").decode("ascii")}]})

binding = {
    "protocol_version": 1,
    "type": BINDING_TYPE,
    "core_instance_id": "core-test-persisted",
    "principal_id": "local-owner",
    "device_id": "dev-test-iphone",
    "nonce": "cd" * 32,
    "request_digest": digest(plain),
    "enrollment_id": "enr-test-generation",
    "app_attest_key_id": base64.b64encode(bytes([1]) * 32).decode("ascii"),
    "approval_key_sha256": "a" * 64,
}
binding_raw = canonical_bytes(binding)

# §4.2: a task body without conversation_ref is byte-identical to the N2 vector;
# with the ref it gains exactly one key.
task_plain = {"scope": "build", "objective": "Prüfe das Café-Layout 👩🏽‍💻 und dokumentiere das Ergebnis.",
              "target_repo": "solvio-demo", "client_request_id": "request-20260910"}
task_ref = dict(task_plain, conversation_ref=CONVERSATION)

# §6.2/§7: the voice-session binding gains conversation_id only when bound.
voice_plain = {"protocol_version": 1, "type": "voice_session_binding", "core_instance_id": "core-test-persisted",
               "device_id": "dev-test-iphone", "session_nonce": "ab" * 32}
voice_bound = dict(voice_plain, conversation_id=CONVERSATION)

vector = {
    "source": "N8_C3_API.md §2.3/§2.4/§4.2/§7 — generated by Tests/conversation_message_vector.py, synthetic identifiers only",
    "domain": DOMAIN.decode(),
    "binding_type": BINDING_TYPE,
    "messages": {
        "plain": {"message": plain, "canonical_hex": canonical_bytes(plain).hex(), "request_digest": digest(plain)},
        "target": {"message": targeted, "canonical_hex": canonical_bytes(targeted).hex(), "request_digest": digest(targeted)},
        "document": {"message": document, "canonical_hex": canonical_bytes(document).hex(), "request_digest": digest(document)},
        "files": {"message": files, "canonical_hex": canonical_bytes(files).hex(), "request_digest": digest(files)},
    },
    "binding": binding,
    "binding_hex": binding_raw.hex(),
    "client_data_hash_hex": domain_hash(DOMAIN, binding_raw),
    "wrong_domain_client_data_hash_hex": {
        "task_start": domain_hash(TASK_DOMAIN, binding_raw),
        "voice_session": domain_hash(VOICE_DOMAIN, binding_raw),
    },
    "challenge": {"nonce": binding["nonce"], "request_digest": digest(plain), "expires_at": 2000000000.0,
                  "binding_b64": base64.b64encode(binding_raw).decode("ascii")},
    "task_body": {
        "without_ref": {"task": task_plain, "canonical_task_hex": canonical_bytes(task_plain).hex(), "request_digest": digest(task_plain)},
        "with_ref": {"task": task_ref, "canonical_task_hex": canonical_bytes(task_ref).hex(), "request_digest": digest(task_ref)},
    },
    "voice_session_binding": {
        "without_conversation": {"canonical_hex": canonical_bytes(voice_plain).hex(),
                                 "client_data_hash_hex": domain_hash(VOICE_DOMAIN, canonical_bytes(voice_plain))},
        "with_conversation": {"conversation_id": CONVERSATION, "canonical_hex": canonical_bytes(voice_bound).hex(),
                              "client_data_hash_hex": domain_hash(VOICE_DOMAIN, canonical_bytes(voice_bound))},
    },
}

if __name__ == "__main__":
    print(json.dumps(vector, indent=2, ensure_ascii=False))
